auth_login:
    path: /auth/login
    handler: Derafu\Auth\Provider\Htpasswd\HtpasswdController::login

auth_logout:
    path: /auth/logout
    methods: [POST]
    handler: Derafu\Auth\Provider\Htpasswd\HtpasswdController::logout
