auth_login:
    path: /auth/login
    handler: Derafu\Auth\Provider\Database\Web\DatabaseController::login

auth_logout:
    path: /auth/logout
    methods: [POST]
    handler: Derafu\Auth\Provider\Database\Web\DatabaseController::logout

auth_profile:
    path: /auth/profile
    methods: [GET]
    defaults: { requires_user: true }
    handler: Derafu\Auth\Account\AccountController::profile
