services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Session configuration.
    Mezzio\Session\SessionMiddleware:
        arguments:
            $persistence: '@Mezzio\Session\SessionPersistenceInterface'

    Mezzio\Session\SessionPersistenceInterface:
        class: Mezzio\Session\Ext\PhpSessionPersistence

    # Flash messages configuration.
    Mezzio\Flash\FlashMessageMiddleware: ~

    # Authentication configuration.
    Mezzio\Authentication\AuthenticationMiddleware: ~
    Mezzio\Authentication\AuthenticationInterface:
        class: Derafu\Auth\Provider\Keycloak\KeycloakAuthentication

    # Keycloak configuration.
    Derafu\Auth\Provider\Keycloak\KeycloakUserRepository: ~
    Derafu\Auth\Provider\Keycloak\KeycloakSessionManager: ~
    Derafu\Auth\Provider\Keycloak\KeycloakConfiguration:
        arguments:
            $config:
                keycloak_url: '%env(default::string:KEYCLOAK_URL)%'
                realm: '%env(default::string:KEYCLOAK_REALM)%'
                client_id: '%env(default::string:KEYCLOAK_CLIENT_ID)%'
                client_secret: '%env(default::string:KEYCLOAK_CLIENT_SECRET)%'
                redirect_uri: '%env(default::string:KEYCLOAK_REDIRECT_URI)%'
                scopes: '%env(default::json:KEYCLOAK_SCOPES)%'
                protected_routes: '%env(default::json:KEYCLOAK_PROTECTED_ROUTES)%'
                callback_route: '%env(default::string:KEYCLOAK_CALLBACK_ROUTE)%'
                logout_route: '%env(default::string:KEYCLOAK_LOGOUT_ROUTE)%'
                logout_redirect_route: '%env(default::string:KEYCLOAK_LOGOUT_REDIRECT_ROUTE)%'
                unauthorized_redirect_route: '%env(default::string:KEYCLOAK_UNAUTHORIZED_REDIRECT_ROUTE)%'
                session_lifetime: '%env(default::int:KEYCLOAK_SESSION_LIFETIME)%'
                secure_cookies: '%env(default::bool:KEYCLOAK_SECURE_COOKIES)%'
                http_client_options:
                    timeout: '%env(default::int:KEYCLOAK_HTTP_TIMEOUT)%'
                    connect_timeout: '%env(default::int:KEYCLOAK_HTTP_CONNECT_TIMEOUT)%'
                    verify: '%env(default::bool:KEYCLOAK_HTTP_VERIFY)%'
                enabled: '%env(default::bool:KEYCLOAK_ENABLED)%'

    # Keycloak controller.
    Derafu\Auth\Provider\Keycloak\KeycloakController:
        public: true
